### ISSUE TITLE
Handling copy and paste events in Firefox

### ISSUE THREAD

**Issue by lutaev** [Bluefieldscom/intl-tel-input#144] opened 2015-01-27 08:44 UTC
I use Mozilla Firefox and when I try to paste some number in phone field nothing happens. But in Google Chrome all is OK.

**Comment by jackocnr** [comment] 2015-01-28 18:53
I just checked [the demo](http://jackocnr.com/intl-tel-input.html) on Firefox v35 on OSX v10.10 and I copied this number `2015555555` and pasted it into the input and it worked fine - does that work for you?

What OS/Browser/version are you on? What plugin initialisation options are you using? What country is selected when you try and paste, and what exact text are you trying to paste?

**Comment by lutaev** [comment] 2015-01-29 11:35
I use Linux Ubuntu 12.04 and version of my Firefox brouser is 35.0.
First I thought that a reason is in my code, but than I ran your demo in Firefox and when I had tryed to paste, I got a red light in input.

**Comment by jackocnr** [comment] 2015-01-30 05:28
How are you pasting? The red light (invalidkey event) only happens in the `keypress` handler which shouldn't fire if you hit Ctrl+v

**Comment by jackocnr** [comment] 2015-02-05 18:06
Closing due to inactivity.

**Comment by Genjo** [comment] 2015-02-16 13:40
Great project!

This bug can be reproduced by copying a phone number (e.g. "(514) 397-1817") and then pasting it by using CTRL + V keybord shortcut into [demo] (http://jackocnr.com/intl-tel-input.html) input on Firefox v.35.0.1 (Windows 7 family premium).
But, if you use right click then paste, it works.

Note: if you paste a wrong number like "(514 397-1817" on Chromium v.42.0.2282.0, the phone will be formatted and corrected, but on Firefox, it won't be.

Hope it helps

**Comment by tamvodopad** [comment] 2015-02-18 14:15
The problem is also relevant for me too.

**Comment by jackocnr** [comment] 2015-02-18 17:21
I think we need to add an extra condition (!e.ctrlKey) to line 367 of intlTelInput.js.

I should have time to do this at some point over the next week. I'm also open to pull requests.

**Comment by jackocnr** [comment] 2015-02-19 05:01
Fixed in v5.1.7

**Closed by jackocnr** 2015-02-19 05:01 UTC
Labels: bug
