### ISSUE TITLE
defaultCountry: "auto" - Failed to load resource

### ISSUE THREAD

**Issue by almogdesign** [Bluefieldscom/intl-tel-input#231] opened 2015-06-08 11:51 UTC
I'm getting the following error when defaultCountry is set to auto

Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://ipinfo.io/?callback=jQuery111208047956700902432_1433756422803&_=1433756422804 Failed to load resource: the server responded with a status of 401 (Unauthorized)

It seems to do with the IP look up and when I go to url I get 
SSL access is restricted to paid plans. See http://ipinfo.io/pricing for more details, or contact us via http://ipinfo.io/contact

**Comment by jackocnr** [comment] 2015-06-08 15:25
Hi there.

What version of the plugin are you using?

Are you using the geoIpLookup option?

Finally, the problem is in the error msg - you are hitting the https
version of ipinfo, which you have to pay for.

I'm getting the following error when defaultCountry is set to auto

Failed to load resource: the server responded with a status of 401
(Unauthorized)
https://ipinfo.io/?callback=jQuery111208047956700902432_1433756422803&_=1433756422804
Failed to load resource: the server responded with a status of 401
(Unauthorized)

It seems to do with the IP look up and when I go to url I get
SSL access is restricted to paid plans. See http://ipinfo.io/pricing for
more details, or contact us via http://ipinfo.io/contact

—
Reply to this email directly or view it on GitHub
<https://github.com/Bluefieldscom/intl-tel-input/issues/231>.

**Comment by almogdesign** [comment] 2015-06-08 19:23
I'mn using International Telephone Input v5.0.1 for the intlTelInput.min.js not seeing a version number just  Protocol Buffer 2 Copyright 2008 Google Inc.

Are you using the geoIpLookup option? -- My understanding is if it's set to auto then it uses the geoIPLookup 

Might be a good idea to have some kind of fallback or default setting

**Comment by jackocnr** [comment] 2015-06-11 09:50
If you're using v5 you wont need to use the getIpLookup option - the ip lookup is hardcoded to use a service called ipinfo.io. If you update to v6, you can completely customise how that works.

I'm guessing your website uses HTTPS (which is why the ipinfo.io call defaults to HTTPS), and if you want to use ipinfo with HTTPS you will have to pay, or maybe if you update the plugin to v6 you can find another service you can use that doesn't charge for HTTPS access, but that's outside the scope of this plugin.

I'm going to close this issue for now, but let me know if you have any other questions.

**Closed by jackocnr** 2015-06-11 09:50 UTC
Labels: question

**Comment by adrianmann** [comment] 2015-10-22 15:45
How customisable is it, like can I specify http://ipinfo.io that easily. Has anyone tried this?

**Comment by jackocnr** [comment] 2015-10-22 18:00
You have complete control over the request as you code it yourself using the `geoIpLookup` function - see the readme.

**Comment by adrianmann** [comment] 2015-10-23 07:06
Ok, but in the source code is there still a `var ipinfoURL = "//ipinfo.io";` that defaults to https on production? Curretly, I am specifying http://ipinfo.io in the `geoIpLookup` method in Version 5.1.6 and it still reverts to using HTTPS via `var ipinfoURL = "//ipinfo.io";`. Thanks for your replies.

**Comment by adrianmann** [comment] 2015-10-23 15:24
Thanks @jackocnr, fantastic stuff. That update to the source coed really opens up the possibilities.
