### ISSUE TITLE
No flag change in Cordova application on Android 

### ISSUE THREAD

**Issue by jmail22** [Bluefieldscom/intl-tel-input#187] opened 2015-03-18 00:02 UTC
Hi

I've got a problem with input field on Android. When I go through Android web browser to the demo it works as it is expected, but when I include that field in the hybrid application - Apache Cordova application - when I input international phone format +48600000000 then the flag doesn't change. 

It works perfectly on other platforms: iOS, Windows Phone, Blackberry 10

Can you please advise me?

J

**Comment by jackocnr** [comment] 2015-03-18 00:08
What device are you on? Which version of Android? Old Android browser, or Chrome? Which version?

**Comment by jmail22** [comment] 2015-03-18 00:13
Samsung Galaxy Note3 - Android 4.4.2 as well as Android 5

Chrome 40.0.2214.109
JavaScript V8 3.30.33.16

**Comment by jackocnr** [comment] 2015-03-18 00:20
Are you setup for remote debugging with Chrome dev tools? https://developer.chrome.com/devtools/docs/remote-debugging#debugging-webviews

Do you see any javascript errors?

**Comment by jmail22** [comment] 2015-03-18 00:24
Yes - I have made the setup - no JavaScript errors have occured

**Comment by jackocnr** [comment] 2015-03-18 00:39
Are you familiar with Chrome dev tools? Could you put a breakpoint on [this line](https://github.com/Bluefieldscom/intl-tel-input/blob/master/build/js/intlTelInput.js#L374) in the keypress handler and step through (step into _handleInputKey, then into setNumber, then into _updateFlagFromNumber) and try to figure out why the flag is not updating?

Also: are you using the utils script? (can you see the placeholder/are you getting formatting?).

**Comment by jmail22** [comment] 2015-03-18 00:44
Yes I am familiar with Chrome tools. I will follow your instructions tommorow (it is middle of the night in Poland) and let you know what have I found.

**Comment by jackocnr** [comment] 2015-03-18 00:45
Thanks dude. BTW I found this: https://issues.apache.org/jira/browse/CB-7503

I suspect the keypress event isn't firing.

**Comment by jmail22** [comment] 2015-03-18 00:49
Yes you are right - I have just checked on Android 4.1.2 (which is not infected by this bug) and it works.

**Comment by jackocnr** [comment] 2015-03-18 02:30
For the record, some notes on this bug:

Present in Android 4.4.2, 4.4.4, L
Not present in 4.1.2
Present with software keyboard
Not present with hardware (i.e. bluetooth) keyboard
Fixed with Chromium M38

**Closed by jackocnr** 2015-03-18 02:30 UTC

**Comment by jmail22** [comment] 2015-03-18 02:35
Why that was closed?

**Comment by jackocnr** [comment] 2015-03-18 02:47
I updated the browser compatibility section of the readme to link to this issue. This is not a bug with this plugin.

**Comment by jmail22** [comment] 2015-03-18 02:55
Ah right - thanks

**Comment by jackocnr** [comment] 2015-03-18 02:55
Go to bed!

**Comment by manjoker** [comment] 2016-07-07 14:49
Hi, i have new problem with windows phone 10, when i type a phone number i have always double digit 
on windows pc, mac, safari, samsung, iphone i don't have this problem but this arrive only on windows phone 10 on windows phone 8 don't have this problem.

thank for your help.

**Comment by jackocnr** [comment] 2016-07-07 14:54
@manjoker please open a new issue for this!
